### PR TITLE
Replace Dockerfile with Alpine version and github action

### LINKED ISSUE #29: connect github to dockerhub for automated builds and pulls

### PR DESCRIPTION
**Pull request by misery**
This fixes #29 and #39

You need to create an account "cutelyst" on dockerhub and a new repository "virtlyst" After that you need to create a token to push build docker images.
This must be added to settings as DOCKERHUB_TOKEN and DOCKERHUB_USERNAME.

Screenshot_20240122_204735

### CODE REVIEW

**Comment by misery** [comment]
That pre-commit stuff should be added as a separated commit.

**Comment by dantti** [comment]
wouldn't it be better to use an ubuntu base and just install the .deb files there? or will docker build the image and have it pre-built? 
iirc DockerHub was removing images with low usage or something like that...

**Comment by misery** [comment]
I added a github action layer caching. That is no problem. Otherwise I could add a package to Alpine.

We will see if it has low usage. 🙂

**Comment by dantti** [comment]
let see if works :)

**Comment by misery** [comment]
```
Error: buildx failed with: ERROR: failed to solve: failed to push cutelyst/virtlyst:latest: push access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

Did you created the repository and added the token/user to github repository action?

**Comment by dantti** [comment]
hmm right, I could not create a cutelyst account since my email was in use, so it's dantti/virtlyst, I thought the DOCKERHUB_USERNAME would be enough

**Pull request merged**
