### PR TITLE
Running Virtlyst in Docker Image

### PR DESCRIPTION
**Pull request by schnuffle**
I created a pull request as I'm not really sure where to start a discussion about the subject. 

This PR  adds some lines to the README to track how I've been able to at least have access to the hosts libvirt environement.

In the end this PR is for discussing the idea of using docker to manage a libvirt host with Virtlyst. 
Using docker-compose might be a better idea.

Can anybody give me an idea what would need to be mapped to the container, to be able to access the console?

Regards

Schnuffle

### CODE REVIEW

**Comment by dantti** [comment]
I prefer that these kind of distro/docker specific stuff to be on the Wiki, possibly with a link on the README file, otherwise the file get's polluted with too much info.

**Comment by candlerb** [comment]
This is a useful start - I now have the container running and can connect to the web interface.

However I'm stuck at authentication: what username/password should be provided?  Giving a system (PAM) username/password doesn't work, nor does empty username/password.  Is this a libvirtd password, or a local virtlyst password?  If so how do I set it?

I'm on ubuntu 18.04 with default configuration of libvirtd.

**Comment by dantti** [comment]
User name is admin, and the passoword is printed when the application creates the sqlite db

**Comment by candlerb** [comment]
Thanks!

Things were a bit broken at first.  I added a local connection type local socket, name "brian-kit".  Then on infrastructure I *once* saw a list of VMs, yay!  But after that it went back to blank, saying "You have no connection".  When I tried to add the connection back again, it silently failed.

At the docker run console I saw:

```
8:9 default[warning] Host id not found or connection not active
8:9 default[warning] Failed to add connection "database is locked"
```

However I then did Ctrl-C followed by `docker start virtlyst` to restart the container, and after that it was fine.  Looks very neat - console access worked first time.

**Comment by dantti** [comment]
Please add this to the Wiki, thanks

**Comment by candlerb** [comment]
When I go to https://github.com/cutelyst/Virtlyst/wiki there is no "Edit" or "New Page" button - but I am logged into github.  Permissions need to be added?

**Comment by dantti** [comment]
please try again, I thought it was open by default.

**Comment by candlerb** [comment]
[Done](https://github.com/cutelyst/Virtlyst/wiki/Running-with-Docker).

**Comment by schnuffle** [comment]
Sorry for being late to the party, had some work going on. 

Thanxs for doing my job 

Regards

Schnuffle

**Pull request closed without merging**
