### PR TITLE
Fix image name and add pull request handling

### PR DESCRIPTION
**Pull request by misery**

### CODE REVIEW

**Comment by misery** [comment]
```Error: Username and password required```

Did you remove the credentials now?

**Comment by dantti** [comment]
no I didn't

**Comment by misery** [comment]
> no I didn't

Ah, I forgot the ```if``` for the login.

**Comment by misery** [comment]
@dantti Ready to merge :-)

Is it possible to ignore that in pre commit?

```
clang-format.............................................................Failed
- hook id: clang-format
- exit code: 1

Configuration file(s) do(es) not support JavaScript: /code/.clang-format
```

**Comment by misery** [comment]
ping? :-)

**Comment by dantti** [comment]
sorry, was on vacations, add it to .gitignore iirc that will do it

**Comment by misery** [comment]
I hope you could relax. :-) .clang-format to .gitignore? Sounds strange... but that would be another pull request. This can be merged. :-)

**Pull request merged**
